language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: "af3c6514d138f5ecdcb93aa5d0245a2f98f88562ba6e128c2abc4c6aff374653"
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: f2W3qM5RhpRKI7i0zSFi+v84vSZX+mDpNvgTHLI2TbXdJE9BwqdjUIsGTbtPgdWUNvMCKyV1SLEI9MrXnq7Gt4LBkYJHj2QQnjc3VBcFhJCT3IVb137rbxGJvUv8RCm2rq3XinMXqhPWKx3lH8tM1hrukJjgt9t/M+Kwv5cuMZWsiUA+bcHkS6s45isSFze/b0TGtP97ShmI6eSQudGnKU0ZnaOowIst9UhYfjtUSbT8BxYKHBY2AXiqwGW/KRhO056r6z4dExQ2m5sIhsDxe913oZNn/jhH74coMY6t0fJvkF4albmKtieuBF8C25GltzEtUOJuAV0ZePnChrezWUqXXueUALz88uiZ6uukBkXNdzVFZTAhoZE69wUDvzVIzBt5ObWqb76BTfV7k92aO/M4c6v/sfaL1Czu7RmvKbqwY1KJiXuRmS6zhaWox4BNdJmmcNueEOjhkobXB2xukMdXTk3fCEN8WDC3AunZuyNt29QybHrhqATPO+Di7sf+EYY/Z0+wHFxdhI1/fPpvXFtKxFqyW5iS+7o2fRZVJfNjrA+2gwF53wHKoxa6/MZWy1rQV+2IwBTP5NALVcY7J4689Rgl9Qfxy091yy1ufdC2QonNRZ0gvhK6xeelV3iQRucSXXzs2TEW3b2mT2bR5w8KLwTiclebNvnLRGVhUCY=
  on:
    tags: true
    branches: true
after_success:
- bash <(curl -s https://codecov.io/bash)
